# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  # build dev site on merged pushes
  push:
    branches: [main, master]
  pull_request:
    types: [opened, reopened, synchronize, labeled]
  # build full site on releases
  release:
    types: [published]
  workflow_dispatch:

name: pkgdown.yaml

jobs:
  pkgdown:
    # For PRs, only run when the PR has the build-website label.
    if: >-
      github.event_name != 'pull_request' ||
      contains(github.event.pull_request.labels.*.name, 'build-website')
    runs-on: ubuntu-latest
    concurrency:
      group: pkgdown-${{ github.event_name == 'pull_request' && github.event.pull_request.number || 'production' }}
      cancel-in-progress: true
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      NOT_CRAN: "true"
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v7

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::pkgdown, local::., stan-dev/pkgdown-config

      - name: Install CmdStan
        run: Rscript -e "cmdstanr::install_cmdstan()"
    
      - name: Build site
        run: |
          pkgdown::build_site_github_pages(
            dest_dir = "docs",
            lazy = FALSE, # change to TRUE if runner times out.
            run_dont_run = TRUE,
            new_process = TRUE
          )
        shell: Rscript {0}

      - name: Get pkgdown destination
        if: github.event_name == 'pull_request'
        id: pkgdown-dest
        run: |
          echo "folder=$(Rscript -e 'cat(fs::path_rel(pkgdown::as_pkgdown(".", override = list(destination = "docs"))$dst_path))')" >> "$GITHUB_OUTPUT"

      - name: Deploy PR preview
        # Forks cannot deploy the site
        if: >
          github.event_name == 'pull_request' &&
          github.event.pull_request.head.repo.full_name == github.repository
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: ${{ steps.pkgdown-dest.outputs.folder }}
          target-folder: pr/${{ github.event.pull_request.number }}
          clean: true
          force: false

      - name: Deploy site
        if: github.event_name != 'pull_request'
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: docs
          clean: false
          force: false
