---
# Github Actions workflow to check CmdStanR
# yamllint disable rule:line-length

name: Unit tests

'on':
  push:
    branches:
      - winarm-gha

jobs:
  winarm-gha:
    runs-on: windows-11-arm

    name: windows-11-arm ('release')
    
    steps:
      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: 'release'

      - name: Check RTools paths
        run: |
          sessionInfo()
          Sys.getenv()
        shell: Rscript {0}

